# Generated by Django 5.0.6 on 2024-05-30 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_mission_slug_profile_slug_task_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
