# Generated by Django 5.0.6 on 2024-05-31 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_remove_waitlist_mission_id_remove_waitlist_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applymission',
            name='numberApplied',
        ),
        migrations.AddField(
            model_name='mission',
            name='numberApplied',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waitlist',
            name='applies',
            field=models.ManyToManyField(to='marketplace.applymission'),
        ),
        migrations.AlterField(
            model_name='applymission',
            name='mission',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='marketplace.mission'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applymission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
