# Generated by Django 5.0.6 on 2024-05-31 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_remove_applymission_numberapplied_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applymission',
            name='AleradyApplied',
            field=models.BooleanField(null=True),
        ),
    ]
