# Generated by Django 5.0.6 on 2024-06-10 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_alter_mission_slug_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='status',
        ),
    ]
