# Generated by Django 5.0.6 on 2024-06-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_remove_mission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='budget',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mission',
            name='numberApplied',
            field=models.IntegerField(null=True),
        ),
    ]
