# Generated by Django 5.0.6 on 2024-06-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_alter_mission_budget_alter_mission_numberapplied'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='thread_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mission',
            name='deadline',
            field=models.DateField(),
        ),
    ]
